[package]
name = "chkos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
mysql_async = "0.32.1"
serde_json = "1.0"
serde = "1.0.160"
warp = "0.3.4"